kind: Template
apiVersion: v1
template: var-notebook
metadata:
  name: var-notebook
objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      name: ${APPNAME}
  spec:
    ports:
      - protocol: TCP
        port: 8888
        targetPort: 8888
    selector:
      name: ${APPNAME}

- kind: Route
  apiVersion: v1
  metadata:
    name: ${APPNAME}
  spec:
    host: ${ROUTE_HOSTNAME}
    to:
      kind: Service
      name: ${APPNAME}

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPNAME}
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      name: ${APPNAME}
    template:
      metadata:
        labels:
          name: ${APPNAME}
      spec:
        containers:
          - name: ${APPNAME}
            image: docker.io/willb/workshop:notebook
            ports:
              - containerPort: 8888
                protocol: TCP

parameters:
  - name: APPNAME
    description: the application name
    value: var-notebook
  - name: ROUTE_HOSTNAME
    description: a hostname for the route
